CS-1202: Need security measure for SugarLive Lambda functions
sugarcrm/SugarLambda pull request #13
Opened 2020-12-04 18:09 UTC by sugarhqi

2020-12-04 22:33 UTC, jimmychen requested changes

2020-12-04 22:33 UTC, jimmychen commented on src/handlers/add-note-to-case.js
> +    const contactId = event.Details.Parameters.contactId;
Since contact id is now required, maybe we can return error right away if it's empty, that way we don't bother to call Rest Api.

2020-12-04 22:33 UTC, jimmychen commented on src/handlers/case-status.js
> +    const contactId = event.Details.Parameters.contactId;
Since contact id is now required, maybe we can return error right away if it's empty, that way we don't bother to call Rest Api.

2020-12-05 00:02 UTC, sugarhqi commented on src/handlers/add-note-to-case.js
> +    const contactId = event.Details.Parameters.contactId;
Done

2020-12-05 00:02 UTC, sugarhqi commented on src/handlers/case-status.js
> +    const contactId = event.Details.Parameters.contactId;
Done

2020-12-05 01:15 UTC, jimmychen approved these changes

2020-12-05 01:15 UTC, jimmychen approved these changes

2020-12-07 18:19 UTC, rogeryang-sugarcrm requested changes

2020-12-07 18:19 UTC, rogeryang-sugarcrm commented on src/handlers/add-note-to-case.js
> +            statusCode: HttpStatus.preconditionFailed
Could we also add the `body` to specify what may be missing?

2020-12-07 18:19 UTC, rogeryang-sugarcrm commented on src/handlers/case-status.js
> +            statusCode: HttpStatus.preconditionFailed
Could we also add the `body` to specify what may be missing?

2020-12-07 18:19 UTC, rogeryang-sugarcrm commented on src/handlers/add-note-to-case.js
> +    const contactId = event.Details.Parameters.contactId || '';
Can this be renamed to `sugarContactId` or similar? I think specifying this will reduce confusion on which contact ID it is using (AWS or Sugar)

2020-12-07 20:00 UTC, sugarhqi commented on src/handlers/add-note-to-case.js
> +            statusCode: HttpStatus.preconditionFailed
Currently none of the three lambda functions called from contact flow are returning this field. To keep it consistent, lets add it to all lambdas in a separate ticket if everybody agrees its necessary.

2020-12-07 20:06 UTC, sugarhqi commented on src/handlers/add-note-to-case.js
> +    const contactId = event.Details.Parameters.contactId || '';
If you are talking about event.Details.Parameters.contactId, its already been used in create-case.js, so I think its better keep using this param name to be consistent.

2020-12-07 21:06 UTC, rogeryang-sugarcrm commented on src/handlers/add-note-to-case.js
> +            statusCode: HttpStatus.preconditionFailed
[CS-1264](https://sugarcrm.atlassian.net/browse/CS-1264) opened to track this

2020-12-07 21:07 UTC, rogeryang-sugarcrm submitted a review, later dismissed
Looks good to me

2020-12-10 07:49 UTC, asaxena-sugarcrm approved these changes

2020-12-10 07:49 UTC, merged