CS-1075
sugarcrm/SugarLambda pull request #3
Opened 2020-10-28 19:34 UTC by jwelborn-sugar

Lambda Function to retrieve call Transcripts and upload them to Sugar

2020-10-29 17:15 UTC, sugarhqi commented on src/handlers/save-transcript.js
> +const httpStatus = {
We have httpstatus in a couple of files now, should we define it in one place?

2020-10-29 17:15 UTC, sugarhqi commented on src/utils/aws/s3-utils.js
> +    var params = {
I didn't add 'no-var' rule to eslint. but since you are using const/let everywhere, you may want to follow the rule here too.

2020-10-29 17:29 UTC, jwelborn-sugar commented on sample.env.json
> +    },
I was thinking if we have them in the same file, later it might be easier to script invoking the functions if we want to since the `--env-vars` file would be the same.

2020-10-29 17:39 UTC, jwelborn-sugar commented on src/handlers/save-transcript.js
> +const httpStatus = {
I'll put them in a util so we can reuse them and add as needed.

2020-10-29 18:19 UTC, sugarhqi approved these changes

2020-10-29 20:33 UTC, rogeryang-sugarcrm requested changes

2020-10-29 20:33 UTC, rogeryang-sugarcrm commented on __tests__/fixtures/transcript.json
> +}
Need a newline

2020-10-29 20:33 UTC, rogeryang-sugarcrm commented on events/save-transcript.json
> +
Need a newline here

2020-10-29 20:33 UTC, rogeryang-sugarcrm commented on template.yml
> +      Description: AWS Lambda Function to get case status by case number
We should update this description

2020-10-29 20:35 UTC, jwelborn-sugar commented on template.yml
> +      Description: AWS Lambda Function to get case status by case number
whoops...

2020-10-29 20:38 UTC, jwelborn-sugar commented on __tests__/fixtures/transcript.json
> +}
I've gotta set up vscode to auto-newline. I take my tools for granted. :(

2020-10-29 20:43 UTC, rogeryang-sugarcrm submitted a review, later dismissed
Looks good to me

2020-11-12 01:15 UTC, jwelborn-sugar commented
@rogeryang-sugarcrm @sugarhqi I lost the reviews on rebasing the PR. Can you re-review if you still approve?

2020-11-12 01:20 UTC, asaxena-sugarcrm approved these changes

2020-11-12 01:21 UTC, merged