CS-829 Save the Call Recording Link for the Phone Call
sugarcrm/SugarLambda pull request #4
Opened 2020-11-02 16:54 UTC by rogeryang-sugarcrm

2020-11-03 13:54 UTC, jwelborn-sugar requested changes

2020-11-03 15:25 UTC, rogeryang-sugarcrm commented on src/utils/aws/s3-utils.js
> +    return event.Records[0].s3.object.key;
Good point! Added a decode to all keys

2020-11-03 15:26 UTC, rogeryang-sugarcrm commented on src/utils/sugar/call-record-utils.js
> +  return url;
The URL partials are already URL safe, but we can be extra safe by encoding the custom parameters

2020-11-03 15:51 UTC, jwelborn-sugar submitted a review, later dismissed

2020-11-03 18:13 UTC, sugarhqi requested changes

2020-11-03 18:13 UTC, sugarhqi commented on src/utils/sugar/call-record-utils.js
> +  return url;
If I understand correctly, we only use this function to construct a url. Why do we need a lambda function and this PR when the same thing can be done on sugar side easily with all the data available in sugar: instance name (from config) and contactId (saved in call record)?

2020-11-03 19:50 UTC, rogeryang-sugarcrm commented
@sugarhqi, for some reason, I can't directly respond to your comment above so I will do it here

The purpose of the Lambda function is to let Sugar know that some call record has a call recording available. We don't know if the contact flow has call recording set up, so we can use a Lambda function that watches the S3 bucket. If we add a call recording link to every call, some links may break if they do not have an audio file

From the Lambda side, we can either send the URL or a flag indicating that there is an available recording

2020-11-06 20:45 UTC, rogeryang-sugarcrm commented on src/utils/sugar/call-record-utils.js
> +  return url;
Per the [comment](https://sugarcrm.atlassian.net/browse/CS-829?focusedCommentId=797202) on CS-829, we have decided that the Lambda function will generate the URL and send it to Sugar

2020-11-12 17:36 UTC, sugarhqi approved these changes

2020-11-12 18:06 UTC, merged