CS-1150 Lambda Function for Sugar Portal Chat
sugarcrm/SugarLambda pull request #6
Opened 2020-11-09 21:30 UTC by jwelborn-sugar

This PR adds an API Gateway, and Lambda Function to serve as an endpoint to start chat client from portal chat.

2020-11-09 21:31 UTC, jwelborn-sugar commented on __tests__/unit/utils/aws/s3-utils.test.js
> +            'Records': [
eslint changes

2020-11-09 21:34 UTC, jwelborn-sugar commented on src/utils/aws/chat-utils.js
> +            'Attributes': body['Attributes'],
This is the only line changed from the provided amazon sample function. The provided sample was hard-coded to only set `customerName` in the attributes, but we'll be able to set multiple attributes with this.

2020-11-10 00:14 UTC, sugarhqi submitted a review, later dismissed

2020-11-10 15:24 UTC, rogeryang-sugarcrm requested changes

2020-11-10 15:24 UTC, rogeryang-sugarcrm commented on template.yml
> +    Default: 12345678-1234-1234-1234-123456789012
I think we should remove this default value. If the user does not enter a value, we should not try to access this contact flow

2020-11-10 15:24 UTC, rogeryang-sugarcrm commented on template.yml
> +    Default: 12345678-1234-1234-1234-123456789012
I think we should remove the default value for similar reasons above

2020-11-10 16:51 UTC, rogeryang-sugarcrm submitted a review, later dismissed
Looks good to me

2020-11-12 18:53 UTC, rogeryang-sugarcrm approved these changes

2020-11-12 18:54 UTC, merged