CS-1125: Lambda function to add a note to a given case
sugarcrm/SugarLambda pull request #8
Opened 2020-11-13 22:47 UTC by pmishra-sugarcrm

2020-11-13 23:59 UTC, sugarhqi approved these changes

2020-11-13 23:59 UTC, sugarhqi commented on src/handlers/add-note-to-case.js
> +            statusCode = HttpStatus.ok;
@jimmy

2020-11-13 23:59 UTC, sugarhqi commented on src/handlers/add-note-to-case.js
> +        status: statusCode,
@jimmy do you want to return {
statusCode: ...,
noteId: ...
}

using the same naming convention as in create-case.js and case-status.js?

2020-11-14 00:24 UTC, jimmychen requested changes

2020-11-14 00:24 UTC, jimmychen commented on src/handlers/add-note-to-case.js
> +        status: statusCode,
Yes let's be consistent. Please use statusCode instead of status, noteId instead of id. Like we did in CS-1165.

2020-11-14 00:24 UTC, jimmychen commented on src/handlers/add-note-to-case.js
> +    console.log('idResponse: '+ JSON.stringify(idResponse));
Do we need this? If it's for debugging purpose, maybe we should remove it.

2020-11-14 00:24 UTC, jimmychen commented on src/handlers/add-note-to-case.js
> +            'parent_type': 'Case',
Should this be 'Cases'?

2020-11-14 00:24 UTC, jimmychen commented on src/handlers/add-note-to-case.js
> +            'name':`Note from ${contactName}`
I think it's better to do some simple checks here. For example if contactName is empty, maybe we can use "Note from customer" instead. Also, if caseBean.id is not empty, may return error, etc.

2020-11-14 00:24 UTC, jimmychen commented on src/handlers/add-note-to-case.js
> +        console.log('noteResponse: '+ JSON.stringify(noteResponse));
Do we need this?

2020-11-14 00:27 UTC, asaxena-sugarcrm commented on events/add-note-to-case.json
> +}
new line.

2020-11-14 01:55 UTC, pmishra-sugarcrm commented on src/handlers/add-note-to-case.js
> +            'parent_type': 'Case',
Good catch thanks, I wonder how it worked with 'Case' though.

2020-11-14 02:47 UTC, pmishra-sugarcrm commented on src/handlers/add-note-to-case.js
> +        status: statusCode,
Made the required changes.

2020-11-14 02:48 UTC, pmishra-sugarcrm commented on src/handlers/add-note-to-case.js
> +    console.log('idResponse: '+ JSON.stringify(idResponse));
This has been added to add logs to cloudwatch, I am using logger-utils here now.

2020-11-14 02:48 UTC, pmishra-sugarcrm commented on src/handlers/add-note-to-case.js
> +            'name':`Note from ${contactName}`
made the required changes here as well

2020-11-14 02:49 UTC, pmishra-sugarcrm commented on src/handlers/add-note-to-case.js
> +        console.log('noteResponse: '+ JSON.stringify(noteResponse));
To log on Cloudwatch

2020-11-14 02:49 UTC, pmishra-sugarcrm commented on events/add-note-to-case.json
> +}
added a new line

2020-11-14 03:02 UTC, jimmychen approved these changes

2020-11-17 18:12 UTC, sugarhqi approved these changes

2020-11-17 18:22 UTC, merged